name: Publish visualization site


on:
  release:
    types: [published]
  push:
    branches:
      - mlperf-inference-results-scc24
      - docs

jobs:

  publish:
    name: Publish the site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository normally
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Configure Git user
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

      - name: Init docs site
        run: INFERENCE_RESULTS_REPO_OWNER=${{ github.repository_owner }} bash run.sh

      - name: Run Mkdocs deploy
        run: mkdocs gh-deploy --force
