# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: MLPerf inference results updater


on:
  push:
    branches: [ "main", "mlperf-inference-results-scc24" ]

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.repository_owner == 'mlcommons'
    env:
      CM_INDEX: "on"
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python3 -m pip install cm4mlops

    - name: Run MLPerf Inference Submission Checker and generate results summary
      run: |
        cm run script --tags=run,mlperf,inference,submission,checker,_short-run --src_version=v4.1 --adr.submission-checker-src.tags=_repo.https://github.com/gateoverflow/inference,_branch.improve_result_generation --quiet --extra_args=" --skip-extra-files-in-root-check"  --submission_dir=./ > >(tee -a out.txt) 2> >(tee -a checker_log.txt >&2)
        cm run script --tags=convert,from-csv,to-md --csv_file=summary.csv --md_file=README.md

        USER="arjunsuresh"
        EMAIL=admin@gateoverflow.org

        git config --global user.name "$USER"
        git config --global user.email "$EMAIL"
        #git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN_TOKEN }}@github.com/${{ github.repository }}
        git add summary*
        echo -e 'Please download [summary.xlsx](summary.xlsx) to view the most recent results. \n ```' > temp
        tail -n 16 checker_log.txt >> temp
        echo -e '\n```\n' >> temp
        cat temp | cat - README.md > temp1
        head -n 100 temp1 > README.md
        git add README.md
        
        git diff-index --quiet HEAD || (git commit -am "Updated results summary" && git push origin)
